networks:
  proxy-network:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    networks:
      - proxy-network
  caddy:
    image: caddy:2.8.4
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      app:
        condition: service_started
    networks:
      - proxy-network