services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: mikhotin/app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=${DATABASE_HOST-db}
      - DATABASE_NAME=${DATABASE_NAME-postgres}
      - DATABASE_USERNAME=${DATABASE_USERNAME-postgres}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD-123}
      - DATABASE_PORT=${DATABASE_PORT-5432}
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres-database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
