services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    extends:
      file: docker-compose.yml
      service: app
    environment:
      NODE_ENV: development
    ports:
      - "8080:8080"
    volumes:
      - .:/app